# 使用文件的方式创建secret的时候需要先base64
# echo -n 'admin' | base64
# echo -n '1f2d1e2e67df' | base64
apiVersion: v1
kind: Secret
metadata:
  name: myscecret
type: Opaque  # /o'pek/ 不透明的
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm